#!/usr/bin/env bash

# This allows to open the online version of the Cable Bible, when the computer
# is connected to the Web, and the local version otherwise.

if [[ "$(uname -s)" = "Darwin" ]] ; then
    if ping -c 1 amiaopensource.github.io >/dev/null 2>&1 ; then
        cablebible_path='https://amiaopensource.github.io/cable-bible/'
    else
        cablebible_path=$(find /usr/local/Cellar/cable-bible -iname 'index.html' | sort -M | tail -n1)
    fi
    open "${cablebible_path}"
elif [[ "$(uname -s)" = "Linux" ]] ; then
    if ping -c 1 amiaopensource.github.io >/dev/null 2>&1 ; then
        cablebible_path='https://amiaopensource.github.io/cable-bible/'
    else
        cablebible_path=$(find ~/.linuxbrew/Cellar/cable-bible -iname 'index.html' | sort -M | tail -n1)
    fi
    xdg-open "${cablebible_path}"
else
    echo "Please locate the 'cable-bible' folder, and open the 'index.html' file in a browser."
fi
